apiVersion: v1
kind: Service
metadata:
  name: svc-active
  namespace: default  # Specify the namespace here
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: rollout-app
